services:
  app:
    image: ghcr.io/erisme/need-whey-app:latest
    container_name: need-whey
    ports:
      - "8003:3000"
    environment:
      DATABASE_URL: "file:/app/data/prod.db"
      AUTH_SECRET: "${AUTH_SECRET}"
    volumes:
      - need-whey-db:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  need-whey-db:
    name: need-whey-db
